### PR TITLE
Reformat the XQuery code so it is consistent and readable

### PR DESCRIPTION
**Pull request by adamretter**

### CODE REVIEW

**Review by chakl — CHANGES_REQUESTED** [review]
Sorry @adamretter I reject to merge that PR.

This PR has the following issues:
- too big - makes it harder to follow design decisions by the PR author
- unstructured - lumps together whitespace changes, function signature changes, and functional changes that might affect operation
- deceptive - these changes are not just "reformatting"

Please consider breaking that PR into ingestible fingerfood.

**Comment by adamretter** [comment]
@chakl it's all formatting apart from two small things:

1. Adding some missing return types to one or two functions.

2. Simplifying element construction in maybe one or two places.

I think the changes are very minor. I'm sorry you feel it's too big. Does the above explanation help you, or do you still need it broken into 3 commits?

**Comment by chakl** [comment]
> do you still need it broken into 3 commits?

Yes, please do.

- make a separate commit for the changes to function signatures. Enforcing signatures *might* affect existing poorly written controllers, so that *could* break things, and applications need to be re-tested. Other than that, I'm fully with you about explicit function signatures.
- make a separate commit for the changes that replace XQuery element construction with inline XML. I did not follow through the original long PR, but I wonder why you suggest these changes? These *should* be behaviorally identical, so what's the gain of changing representation X to representation Y?
- the remainder should only contain functionally irrelevant whitespace changes or minor typo fixes.

**Comment by adamretter** [comment]
@chakl As requested, I have now broken this down into a number of smaller atomic commits. Could you take another look please?

**Review by marmoure — APPROVED** [review]

**Review by dizzzz — APPROVED** [review]

**Pull request merged**
