### PR TITLE
Correct the required version of the Crypto module and eXist-db

### LINKED ISSUE #8: [BUG] No version for EXPath Crypto dependency
The existdb-saml EXPath Package (including the latest version  1.6.3) does not declare the version of the EXPath Crypto module that it depends on.

The `expath-pkg.xml` in the XAR file, only contains this:
```xml
<package xmlns="http://expath.org/ns/pkg" name="http://exist-db.org/xquery/exsaml" abbrev="existdb-saml" version="1.6.3" spec="1.0">
    <title>existdb-saml</title>
    <dependency package="http://expath.org/ns/crypto"/>
    <dependency processor="http://exist-db.org" semver-min="3.2.0"/>
</package>
```

The dependency on `http://expath.org/ns/crypto` should declare at least a `semver-min`.

There have been lots of differing version of the EXPath Crypto module (published for eXist-db), including crypto versions: `6.0.1`, `6.0.0`, `5.3.0`, `1.0.0`, `0.7`, `0.6`, `0.5`, `0.3.5`, and `0.3.4`.

The `existdb-saml` module declares that it requires eXist-db version 3.2.0 or later. The version of EXPath Crypto for eXist-db 3.2.0 (i.e. 0.3.5) however does not appear to work with the `existdb-saml` module on eXist-db 6.1.0. See https://exist-db.org/exist/apps/public-repo/packages/crypto?eXist-db-min-version=3.2.0

## Questions
1. Which is the version that is meant to be used by existdb-saml please?
2. Does the semver-min of eXist-db used by the existdb-saml module need to be updated perhaps?

### PR DESCRIPTION
**Pull request by adamretter**
Closes https://github.com/eXist-db/existdb-saml/issues/8

### CODE REVIEW

**Comment by joewiz** [comment]
LGTM

**Comment by adamretter** [comment]
@chakl Can you take a look at this one please?

**Review by marmoure — APPROVED** [review]
LGTM

**Comment by adamretter** [comment]
> LGTM

@joewiz Would you be able to add your approval to your review please?

**Review by marmoure — APPROVED** [review]

**Review by dizzzz — APPROVED** [review]

**Pull request merged**
